### ISSUE TITLE
Uses wrong ascProvider / teamId?

### ISSUE THREAD

**Issue by YanDevDe** [electron/notarize#101]
I have multiple organization in my apple developer account. So the logical reason would be using teamId.

I was using following scripts:

```js
require('dotenv').config();
const { notarize } = require('electron-notarize');

exports.default = async function notarizing(context) {
    const { electronPlatformName, appOutDir } = context;
    const appName = context.packager.appInfo.productFilename;
    console.log("PROVIDER", process.env.APPLE_ID_PROVIDER);
    return await notarize({
        tool: "notarytool",
        appBundleId: process.env.appId,
        appPath: `${appOutDir}/${appName}.app`,
        appleId: process.env.APPLE_ID,
        appleIdPassword: process.env.APPLE_ID_PASS,
        teamId: process.env.APPLE_ID_PROVIDER,
    });
};
```

And it sign successfully / no error were thrown - EXCEPT that the sign result is using wrong teamId. It uses automatically my own account teamId instead from the company's team Id which is set to `process.env.APPLE_ID_PROVIDER`. And I'm very sure that I've entered it correctly because the console.log("PROVIDER", ...) shows the correct company's team Id I wanted to have. "identityName=<Developer ID Application: *>" also shows the wrong team Id.

I've tried the legacy and notarytool, none of them were using the provider provided from "ascProvider" or "teamId", both were the same result.

**Comment by MarshallOfSound** [comment]
This sounds like a bug in `notarytool`, we won't invent a team ID to use 😅 Especially not one that happens to be valid.

I'd suggest replicating by spawning notarytool yourself and reporting to apple as a bug
