### ISSUE TITLE
notarytool mode fails if ascProvider argument not present

### ISSUE THREAD

**Issue by relativityboy** [electron/notarize#106]
electron-notarize 1.2.1

When running 
```
return await notarize({
        tool:'notarytool',
        appBundleId,
        appPath,
        appleId: process.env.APPLE_ID,
        appleIdPassword: process.env.APPLE_ID_PASSWORD,
        teamId: process.env.APPLE_ID_GROUP_SHORT_NAME
    });
```
 The notarize fails with the following error
 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/599528/164249866-f1047de4-5d40-4140-b451-2e1f05c9b008.png">

The docs indicate ascProvider is required only for the legacy mode.

If I swap out `teamId` for `ascProvider` I get a similar error. 

`notarize` needs to be updated to only check for relevant arguments for the selected mode.

**Comment by deggertsen** [comment]
Is it because you are providing the "appBundleId"? I don't think you are supposed to provide that with the notarytool method.

**Comment by relativityboy** [comment]
@deggertsen - Looks like Apple's use of notary tool still requires it. 

Screenshot is from https://developer.apple.com/videos/play/wwdc2021/10261/

<img width="815" alt="image" src="https://user-images.githubusercontent.com/599528/164799647-e5224abb-17a0-43e6-af9e-d5ef61a5c0ac.png">

**Comment by MarshallOfSound** [comment]
> Is it because you are providing the "appBundleId"? I don't think you are supposed to provide that with the notarytool method.

This is potentially correct, `appBundleId` is only required when using the `legacy` tool
