### ISSUE TITLE
Error: HTTP status code: 401. Unauthenticated. Ensure that all authentication arguments are correct.

### ISSUE THREAD

**Issue by penghui** [electron/notarize#110]
My CI server keeps building successfully for more than a month, but today I got an error when on notarizing. The error message is 
```
Error: HTTP status code: 401. Unauthenticated. Ensure that all authentication arguments are correct.
```
I tried change my apple id's app-specific password, but still the same error.
I google it, but no valuable information found。
Does anyone have a clue on it?

Update:
After change options 'tool' from notarytool back to legacy, everything works fine.
So I guess that's Apple's issue.

**Comment by NKnife** [comment]
use keychainProfile
https://github.com/electron/notarize/issues/92
