### ISSUE TITLE
Fail to notarize app

### ISSUE THREAD

**Issue by juli1** [electron/notarize#111]
Hi,

I am trying to notarize my app. I put the appId correctly and also added all the correct environment variables. I am getting this error. What are the best ways to troubleshoot this?

```
Start notarizing io.codiga.assistant.Codiga found at /Users/runner/work/electron-app/electron-app/release/build/mac-arm64/Codiga.app
  ⨯ The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Error  failedTask=build stackTrace=TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Error
    at Object.writeFileSync (fs.js:1522:5)
/Users/runner/work/_actions/samuelmeuli/action-electron-builder/v1/index.js:144
				throw err;
    at module.exports (/Users/runner/work/electron-app/electron-app/node_modules/electron-builder-notarize/index.js:99:6)
```

**Comment by yles9056** [comment]
I think this happens when the notarizing fails. It seems that electron-builder-notarize cannot retrieve the error message properly.

You can use the following command in terminal to check if the notarizing has failed:
`xcrun altool --notarization-history 0 -u "your appleId" -p "your appleId password"`

**Comment by zalenskiSofteq** [comment]
Yesterday build failed with the same error. Today build was passed without any changes.
I don't know what the reason was.

**Comment by jaymartinez** [comment]
Can you please explain what needs to go into the "appleApiKey" property? Your docs just say "string", is it supposed to be the path to the p8 file, the actual key value, or what? Thanks.

await notarize({
    tool: 'notarytool',
    appBundleId: build.appId,
    appPath: `${appOutDir}/${appName}.app`,
    appleApiKey: './private_keys/AuthKey_<blah>.p8',
    appleApiKeyId: 'myapikeyid',
    appleApiIssuer: 'myissuerid'
  });

**Comment by MarshallOfSound** [comment]
https://github.com/electron/notarize#notes-on-jwt-authentication
