### ISSUE TITLE
The staple and validate action failed! Error 65.

### ISSUE THREAD

**Issue by r0hin** [electron/notarize#120]
Stapling the app using electron-builder afterSign hook and the following script:
```
await electron_notarize.notarize({
  tool: "notarytool",
  appBundleId: appId,
  appPath: appPath,
  appleId: process.env.APPLE_ID,
  appleIdPassword: process.env.APPLE_ID_PASSWORD,
  teamId: process.env.APPLE_TEAM_ID,
});
```
Yeilds this error for me:
```
CloudKit query for Parallel.app (2/de1888131cc20e39522d0986cb6fe9cab1d86146) failed due to "Record not found".
Could not find base64 encoded ticket in response for 2/de1888131cc20e39522d0986cb6fe9cab1d86146
The staple and validate action failed! Error 65.
```
I am running MacOS Ventura 13.0.1. Thank you!

**Comment by andirsun** [comment]
@r0hin did you solve the issue ?

**Comment by r0hin** [comment]
I haven’t yet unfortunatelyOn Dec 2, 2022, at 12:42 PM, Anderson Laverde ***@***.***> wrote:﻿
@r0hin did you solve the issue ?

**Comment by Abisco** [comment]
Hey any chance you figured it out as of yet? Am running into the same issue.

**Comment by CodyQuiz** [comment]
Any updates here? Running into the same issue

**Comment by r0hin** [comment]
What I did was I installed Xcode separately and manually used `notarytool` and `stapler` to notarize, which seemed to work. Seems there is a disconnect between that process and this library somewhere.

**Comment by CodyQuiz** [comment]
@r0hin ty for updates. Seems like i should do the same. 
But also looks like the issue is still actual.

**Comment by fluke777** [comment]
Anyone had any luck here? I am seeing the same thing on Monterey M2.

**Comment by CodyQuiz** [comment]
> Anyone had any luck here? I am seeing the same thing on Monterey M2.

As for me I realized that i used wrong certificate. I tried to notarize app that will distribute outside the app store with certificate for app store. After I added correct one the issue was solved. So it's just was my miskate. Not sure that it can help someone but at least helps to avoid same error.

**Comment by fluke777** [comment]
My conclusion is also that this could be a wrong certificate.

The issue is that the notarize function will return 0 and the json response indicates that is invalid. electron/notarize does not parse the json and always proceeds to try to staple which fails. You can try yourself with something like this.

```
cd dist/mac-universal
ditto -c -k --sequesterRsrc --keepParent 'App.app' '${HOME}/app/App.zip'
xcrun notarytool submit "./App.zip" --apple-id "user" --password "pass" --team-id "team" --wait --output-format json 
```

@CodyQuiz Out of curiosity what type of certificate are you using? I think I used "Apple Development". I would also like to distribute outside of appstore as a standalone app.

**Comment by CodyQuiz** [comment]
> My conclusion is also that this could be a wrong certificate.
> 
> The issue is that the notarize function will return 0 and the json response indicates that is invalid. electron/notarize does not parse the json and always proceeds to try to staple which fails. You can try yourself with something like this.
> 
> ```
> cd dist/mac-universal
> ditto -c -k --sequesterRsrc --keepParent 'App.app' '${HOME}/app/App.zip'
> xcrun notarytool submit "./App.zip" --apple-id "user" --password "pass" --team-id "team" --wait --output-format json 
> ```
> 
> @CodyQuiz Out of curiosity what type of certificate are you using? I think I used "Apple Development". I would also like to distribute outside of appstore as a standalone app.

First i used Apple Distribution and it caused the error 65. Then I switch to the Developer ID Application certificate and it works fine.

**Comment by Abisco** [comment]
> > My conclusion is also that this could be a wrong certificate.
> > The issue is that the notarize function will return 0 and the json response indicates that is invalid. electron/notarize does not parse the json and always proceeds to try to staple which fails. You can try yourself with something like this.
> > ```
> > cd dist/mac-universal
> > ditto -c -k --sequesterRsrc --keepParent 'App.app' '${HOME}/app/App.zip'
> > xcrun notarytool submit "./App.zip" --apple-id "user" --password "pass" --team-id "team" --wait --output-format json 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @CodyQuiz Out of curiosity what type of certificate are you using? I think I used "Apple Development". I would also like to distribute outside of appstore as a standalone app.
> 
> First i used Apple Distribution and it caused the error 65. Then I switched to the Developer ID Application certificate and it works fine.

Yup sorry for late reply but this fixed it for me too

**Comment by fluke777** [comment]
@chasepeeler I have not figured out how you pick a specific certificate (not saying this is impossible). What exactly are you struggling with? I am also a beginner but today I was able to sign and notarize so I feel semi knowledgeable :-)

**Comment by chasepeeler** [comment]
I actually figured it out. I didn't have the right kind of certificate. Once I got that taken care of, it worked.

**Comment by danishin** [comment]
I also fixed it by using `Developer ID Application` not `Apple Distribution` (one I used for ios distribution) as mentioned in https://github.com/electron/notarize/issues/120#issuecomment-1382039042 and https://www.electronforge.io/guides/code-signing/code-signing-macos#obtaining-signing-certificates

**Comment by FilipMasar** [comment]
@danishin How do you tell electron/notarize which certificate to use? I am having the same issue but I still haven't figured it out.
I am part of 2 apple development teams
1. Team where we develop mobile app and we distribute it through App Store
2. Team where I am creating desktop app which will be distributed outside of App Store - I want to sign the app under this team

**Comment by danishin** [comment]
@FilipMasar you can set it via `identity` as mentioned in https://github.com/electron/osx-sign#code-signing and https://js.electronforge.io/modules/_electron_forge_shared_types.InternalOptions.html#OsxSignOptions

**Comment by MarshallOfSound** [comment]
Ah yeah, I'm not sure there is anything we can do in `@electron/notarize` to automatically detect this but notarization only works on "Developer ID" certificates so you have to be sure you're using the right type of certificate

**Comment by zhaozailin** [comment]
My solution was that I found three Apple Root CA - G3 in the keychain, but none of them were checked. After I deleted two, the last one became checked, and re-signing and notarization succeeded.

**Comment by pq-dong** [comment]
> My solution was that I found three Apple Root CA - G3 in the keychain, but none of them were checked. After I deleted two, the last one became checked, and re-signing and notarization succeeded.

For me, this works.
