### ISSUE TITLE
Team is not yet configured for notarization.

### ISSUE THREAD

**Issue by gv1122** [electron/notarize#132]
I am trying to notarize my electron app with this package, however, i keep getting this error:
`Error: Unrecognized notarization status: "rejected:`

after some more digging, its because apple is returning:
`Team is not yet configured for notarization.`

anyone encounter a similar issue, it was working fine until just today, very odd.

**Comment by ktym4a** [comment]
@gv1122 did you solve the issue?

**Comment by MarshallOfSound** [comment]
@gv1122 This normally means you have new things to "sign" in your apple developer account.  Agreements, new terms of use, etc.
