### ISSUE TITLE
Include notarization log in debug output regardless of notarization result

### ISSUE THREAD

**Issue by larrywalters** [electron/notarize#139]
According to [Apple's documentation](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool#Fetch-the-notary-log), it is recommended to always check the notarization log, even if the request succeeds. This is because there may be warnings included which would be helpful to the developer(s). It makes sense therefore to always print the log in the debug output.

Therefore, I suggest making the following change in `notarytool.ts`:
<img width="866" alt="ProposedDff" src="https://github.com/electron/notarize/assets/18539667/f3e20da4-6b5c-4d27-bf98-30286be50c01">

**Comment by nikwen** [comment]
Great idea! What do you think about submitting your change as a PR?

**Comment by MarshallOfSound** [comment]
PRs welcome 💯
