### ISSUE TITLE
Stuck on uploading zip to apple

### ISSUE THREAD

**Issue by yonathan06** [electron/notarize#146]
I tried running notarize through github ci, and it is stuck on uploading the zip file to apple server
It worked yesterday, not sure if a patch was released that changed something, or if it is an error on apple servers

```
electron-notarize:spawn spawning cmd: xcrun args: [
'notarytool',
'submit',
'/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-notarize-733mVx/MyApp.zip',
'--apple-id',
'*********',
'--password',
'*********',
'--team-id',
'*********',
'--wait',
'--output-format',
'json'
] opts: {}
```

**Comment by yonathan06** [comment]
solved, probably a hiccup in apple server

**Comment by baparham** [comment]
Is there a way to submit, get the UUID back, and then check again later on in another workflow job or something? I really wouldn't want this sort of delay eating up minutes of my CI time, 5-15minutes is already pushing it kind of high as Apple's communicated default for how long this should take, but it could be hours.

**Comment by Zedbyte-corp** [comment]
The above issue occurs for me.. its been 2 days

This is the log im getting so far https://pastebin.com/4mAaNRvk

**Comment by raphaelmenges** [comment]
Did the problem resolve for you? For me, the same seems to happen. Everything looks good but the process gets stuck at the very same step of or after app submission. Is there anything to check via `electron-notarize` or in the apple developer account?
