### ISSUE TITLE
'tool: "notarytool"' won't work

### ISSUE THREAD

**Issue by sprout2000** [electron/notarize#150]
* **Electron-Builder Version**: 24.6.2
* **@electron/notarize Version**: 2.1.0
* **@electron/osx-sign Version**: 1.0.4
* **macOS version**: 13.4.1 (c) Ventura

* **Node Version**: 18.16.1

* **Electron Version**: 25.3.1

Legacy altool mode is used even if 'tool: "notarytool"' is specified in the notarize script.

```typescript
const notarizer = async (context: AfterPackContext) => {
  const { appOutDir } = context;
  const appName = context.packager.appInfo.productFilename;

  return await notarize({
    tool: "notarytool",
    appPath: `${appOutDir}/${appName}.app`,
    teamId: `${process.env.TEAM_ID}`,
    appleId: `${process.env.APPLE_ID}`,
    appleIdPassword: `${process.env.APPLE_APP_SPECIFIC_PASSWORD}`,
  });
};

export default notarizer;
```

Output to the console is as follows:

```sh
Notarizing using the legacy altool system. The altool system will be disabled on November 1 2023. Please switch to the notarytool system before then.
You can do this by setting "tool: notarytool" in your "@electron/notarize" options. Please note that the credentials options may be slightly different between tools.
```

**Comment by MarshallOfSound** [comment]
> Legacy altool mode is used even if 'tool: "notarytool"' is specified in the notarize script.

Please provide a full sample that reproduces this (without using electron-builder).  There are countless projects using `notarytool` just fine 😅 not sure why yours wouldn't
