### ISSUE TITLE
Possiblity to pass appleApiKey as base64 string

### ISSUE THREAD

**Issue by KillerCodeMonkey** [electron/notarize#181]
Just a short question:

Is it possible to extend this wonderful tool to allow to pass the appleApiKey as a base64 string instead of a path?

Would be nice to allow using API-Keys in CI without the need of putting the file somewhere "unsafe".

E.g. in github actions just put the base64 content in a secret and use it there.

Thanks :)

**Comment by jannemecek** [comment]
I wish this was possible as well

**Comment by MarshallOfSound** [comment]
We didn't choose this API, the `notarytool` command that actually submits stuff to apples servers takes in a parameter which is a filepath 🤷 We could wrap that into a "pass us the content" in our API, but then the "unsafe" behavior of writing it to disk would still occur you just wouldn't be aware it was happening which is IMO worse

```
OVERVIEW: Submit an archive to the Notary service

USAGE: notarytool submit [<options>] <file-path>

ARGUMENTS:
  <file-path>             Path to the archive

OPTIONS:
  -v, --verbose
  -k, --key <key>         App Store Connect API key. File system path to the private key.
```
