### ISSUE TITLE
Error when launching signed and notarized app - JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by michaelburris** [electron/notarize#185]
When launching an app that has been osx signed and notarized I get the following error:

```
Uncaught Exception:
Error: Knex: run
$ npm install sqlite3 --save
dlopen(/var/folders/..., 0x0001): tried: '/var/folders/....' (code signature in <> '.....' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '......' (no such file)
```
I'm hoping someone has had to deal with this using knex.js and electronjs. The app works fine when its not notarized and signed.

**Comment by Lsnsh** [comment]
+1 same problem.

**Comment by miketaheny** [comment]
Same problem here.  Either of you come up with a resolution? @michaelburris @Lsnsh

**Comment by Lsnsh** [comment]
> Same problem here. Either of you come up with a resolution? @michaelburris @Lsnsh

@miketaheny After setting `com.apple.security.cs.disable-library-validation`, worked normally for me.

```xml
<key>com.apple.security.cs.disable-library-validation</key>
<true/>
```

https://developer.apple.com/forums/thread/126895

**Comment by miketaheny** [comment]
@Lsnsh - that worked thank you!
For anyone using electron forge this fixed the error with dlopen(.... different team Ids.
-------
**1.** Add entitlements.plist to the root of your project. 
`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
  </dict>
</plist>`

**2.** n forge.confing.js add this to osxSign:
`      optionsForFile: (filePath) => {
        // Here, we keep it simple and return a single entitlements.plist file.
        // You can use this callback to map different sets of entitlements
        // to specific files in your packaged app.
        return {
          entitlements: './entitlements.plist'
        };
      }`

**Comment by michaelburris** [comment]
@miketaheny @Lsnsh  Thank you. Works as advertised.
