### ISSUE TITLE
Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by akshitcompro** [electron/notarize#186]
We are facing the below error on using @electron/notarize v2.3.0

<img width="481" alt="image" src="https://github.com/electron/notarize/assets/85864914/30561c03-9e91-41c6-bc61-57db52e7b789">

Not sure, what's the actual issue here. We are providing all the required params to the notarize function:

<img width="222" alt="image" src="https://github.com/electron/notarize/assets/85864914/6bbee291-9382-4002-8d96-4fa97906ebad">

**Comment by Chamarsh** [comment]
Having the same issue

**Comment by rotu** [comment]
This is the same issue as #177.

**Comment by yingchen-liu** [comment]
Same here

**Comment by yingchen-liu** [comment]
Looks like it is trying to parse a JSON that is not actually a JSON. `notarytool` returns a string instead of JSON when there is an error occurs.
I modified the `node_modules/@electron/notarize/lib/notarytool.js` file to make it throw an error with the JSON string, so that I can see the actual error message from Apple.
```
const result = yield (0, spawn_1.spawn)('xcrun', notarizeArgs);

throw new Error(result.output.trim());

const parsed = JSON.parse(result.output.trim());
```
For me the error is "Error: HTTP status code: 403. Invalid or inaccessible developer team ID for the provided Apple ID. Ensure the Team ID is correct and that you are a member of that team."

**Comment by andelf** [comment]
Turned out that you need to sign some new agreement on Apple Developer site.

**Comment by EternallLight** [comment]
Strangely, it still fails for me when using the plugin as is. 

This change in `node_modules/@electron/notarize/lib/notarytool.js` magically fixes it for me:

```js
            const result = yield (0, spawn_1.spawn)('xcrun', notarizeArgs);
            console.log('Attempting to parse that crap:', result.output.trim());
            let parsed;
            try {
                parsed = JSON.parse(result.output.trim());
            } catch (e) {
                console.error("Failed to parse JSON:", e);
                throw new Error(result.output.trim());
            }
```

**Comment by warrenday** [comment]
Had the same issue, currently forking the repo to apply the above fix.

**Comment by warrenday** [comment]
Rollback to version 2.2.0 where JSON is parsed correctly.

"@electron/notarize": "2.2.0"

Also be sure to add resolutions to your package.json so your other electron packages use the correct version.

"resolutions": {
    "@electron/notarize": "2.2.0"
  }

**Comment by therockerline** [comment]
Ok, with the rollback to 2.2.0 the error has changed. now it says "Error: HTTP status code: 401. Not authenticated. Make sure all authentication arguments are correct." but when I run notarize locally everything is fine. The problem occurs only on gitactions. I use the three environment variables:
```
APPLE_API_KEY: ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
APPLE_API_KEY_ID: ${{ secrets.api_key_id }}
APPLE_API_ISSUER: ${{ secrets.api_key_issuer_id }}
```

**Comment by cpvalente** [comment]
> Turned out that you need to sign some new agreement on Apple Developer site.

Hi @andelf, can you provide more feedback as to what was missing?

**Comment by remloyal** [comment]
I am encountering the same problem. May I ask if there is any way to solve it?

**Comment by cpvalente** [comment]
I have encountered this issue in my attempts. Leaving this here as it may help someone else.

The error for me happened when the notarize function tried to parse the response from the initial request.
In my case, it ended up being an issue with authentication as my Apple ID was wrong, so it return an error message ( `Error: HTTP status code: 401. Invalid credentials`... hence the start with `E`)

I guess `electron-notarize` could be more helpful in providing a better error as suggested in #191

**Comment by austinlangdon** [comment]
> Turned out that you need to sign some new agreement on Apple Developer site.

Thank you

I was also able to fix this by logging into my [Apple Developer account](https://developer.apple.com/account) and accepting the updated agreement.

**Comment by rotu** [comment]
This should be fixed by #191

**Comment by Igloczek** [comment]
If someone like me ended here today looking for solutions, make sure to `npm update @electron/notarize` and, as stated before, accept new terms on the Apple side of things.

**Comment by stevebauman** [comment]
For anyone else looking for quick link, go to https://appstoreconnect.apple.com/business and accept any agreements you have there 👍
