### ISSUE TITLE
Forward errors to stderr so users can debug issues

### ISSUE THREAD

**Issue by benjaffe** [electron/notarize#19]
I got the error `Failure! Error: Failed to check status of notarization request: ...`

Running the `xcrun altool --notarization-info ...` command manually, I saw this error:
`Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.`

Perhaps this tool could be better about either forwarding the error to stdout, or handling this error specifically, since in my case at least, there's a clear action the user needs to take, and I couldn't have known without reading the source of `electron-notarize` to track down the error manually..

**Comment by SeungjongHan** [comment]
#14

**Comment by benjaffe** [comment]
I don't think #14 actually addresses this. This issue is about the user not having signed the necessary agreements in XCode, and not swallowing that error.

**Comment by MarshallOfSound** [comment]
`DEBUG=electron-notarize*` will display stderr output
