### ISSUE TITLE
Electron forge hangs after Application signed

### ISSUE THREAD

**Issue by ghoshbishakh** [electron/notarize#197]
I am facing a strange problem. From debug log it appears that the code signing works perfectly. But the electron forge packaging does not proceed:

<img width="1436" alt="image" src="https://github.com/electron/notarize/assets/5156787/a8d369ae-d446-4ec5-8f68-6713e79a77f7">

**Comment by erickzhao** [comment]
Hey @ghoshbishakh, Notarization is a separate step that uploads your app to Apple's servers and receives a notarization ticket from them after it's been processed.

This process may take a few minutes, although Apple claims that 98% of apps are successfully notarized within 15 minutes.

Debug logs for the notarization step can be collected using `DEBUG=electron-notarize*`.

**Comment by ghoshbishakh** [comment]
Thank you for the response @erickzhao . It seems that the apple server was not responding that day.
Next day it started working, although I had also updated all the packages related to electron forge and others to the latest version.

Thanks.
