### ISSUE TITLE
Exported TypeScript types breaking change in 1.1.0

### ISSUE THREAD

**Issue by malept** [electron/notarize#84]
It appears that #82 made a breaking change to the exported types. `src/index.ts` no longer exports `NotarizeCredentials` and `TransporterOptions` which Electron Packager was using in its TypeScript definition.

Example of the breakage: https://github.com/electron-userland/electron-forge/pull/2434/checks?check_run_id=3284856055

**Comment by malept** [comment]
Also it seems that we can't migrate to using `NotarizeOptions` because that is also not exported.

**Comment by davidrusu** [comment]
@malept can this be closed?

**Comment by malept** [comment]
No, the breakage still exists. This can be closed when 2.0.0 is released.

**Comment by MarshallOfSound** [comment]
`2.0.0` is released and the types are exported
